/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SweetsRouteImport } from './routes/sweets'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrasadamsRouteImport } from './routes/prasadams'
import { Route as HotItemsRouteImport } from './routes/hot-items'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AllItemsRouteImport } from './routes/all-items'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SweetsRoute = SweetsRouteImport.update({
  id: '/sweets',
  path: '/sweets',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrasadamsRoute = PrasadamsRouteImport.update({
  id: '/prasadams',
  path: '/prasadams',
  getParentRoute: () => rootRouteImport,
} as any)
const HotItemsRoute = HotItemsRouteImport.update({
  id: '/hot-items',
  path: '/hot-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AllItemsRoute = AllItemsRouteImport.update({
  id: '/all-items',
  path: '/all-items',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-items': typeof AllItemsRoute
  '/contact': typeof ContactRoute
  '/hot-items': typeof HotItemsRoute
  '/prasadams': typeof PrasadamsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialties': typeof SpecialtiesRoute
  '/sweets': typeof SweetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-items': typeof AllItemsRoute
  '/contact': typeof ContactRoute
  '/hot-items': typeof HotItemsRoute
  '/prasadams': typeof PrasadamsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialties': typeof SpecialtiesRoute
  '/sweets': typeof SweetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-items': typeof AllItemsRoute
  '/contact': typeof ContactRoute
  '/hot-items': typeof HotItemsRoute
  '/prasadams': typeof PrasadamsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialties': typeof SpecialtiesRoute
  '/sweets': typeof SweetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/all-items'
    | '/contact'
    | '/hot-items'
    | '/prasadams'
    | '/sitemap.xml'
    | '/specialties'
    | '/sweets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/all-items'
    | '/contact'
    | '/hot-items'
    | '/prasadams'
    | '/sitemap.xml'
    | '/specialties'
    | '/sweets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/all-items'
    | '/contact'
    | '/hot-items'
    | '/prasadams'
    | '/sitemap.xml'
    | '/specialties'
    | '/sweets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllItemsRoute: typeof AllItemsRoute
  ContactRoute: typeof ContactRoute
  HotItemsRoute: typeof HotItemsRoute
  PrasadamsRoute: typeof PrasadamsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialtiesRoute: typeof SpecialtiesRoute
  SweetsRoute: typeof SweetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sweets': {
      id: '/sweets'
      path: '/sweets'
      fullPath: '/sweets'
      preLoaderRoute: typeof SweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prasadams': {
      id: '/prasadams'
      path: '/prasadams'
      fullPath: '/prasadams'
      preLoaderRoute: typeof PrasadamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-items': {
      id: '/hot-items'
      path: '/hot-items'
      fullPath: '/hot-items'
      preLoaderRoute: typeof HotItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-items': {
      id: '/all-items'
      path: '/all-items'
      fullPath: '/all-items'
      preLoaderRoute: typeof AllItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllItemsRoute: AllItemsRoute,
  ContactRoute: ContactRoute,
  HotItemsRoute: HotItemsRoute,
  PrasadamsRoute: PrasadamsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialtiesRoute: SpecialtiesRoute,
  SweetsRoute: SweetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
